### ISSUE TITLE
Mob nametags dissapear

### ISSUE THREAD

**Issue by Joeythemlgprogamer11** [Zrips/MobFarmManager#12]
Mobs name tags dissapear when mobs enter a capped area https://s.amsu.ng/XAnP7PdZ55EN

**Comment by Joeythemlgprogamer11** [comment]
https://docs.google.com/document/d/1hfT5zt6TcqoP6lZKGon3C2jmMLTH425C-hMNjUVNOJo/edit?usp=drivesdk

**Comment by Zrips** [comment]
MFM doesn't modify entities name tags in any shape or form. It only checks them if we want to exclude named entities from cleanup. But you might want to check out other plugins which could be doing something weird with mobs when they change chunk area.
