### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AlfreDGR** [Zrips/MobFarmManager#13]
Hi, we have set the limit of villagers to 30 per chunk. We spawn 30 villagers in one chunk and then to spawn another villager it has to be two chunks far away from the one that has the 30 villagers. How can we set that it has to be only one chunk far away instead of two chunks to spawn more villagers?

**Comment by Zrips** [comment]
Disable GroupChunks or set GroupChunksRadius to 1. But I would recommend to keep this enabled  and at 2 and simply increase villager limit. This in general is essential when it comes in detecting bunches of mobs in 2x2 area which is located in 4 separate chunks, with this enabled even if its in different chunk we will still apply same limit which will minimize people abusing this system and lower overall server load.
