### ISSUE TITLE
1.16.4 Mobcap not work as before if you use entity group and individual entity types in 1.5.9.0

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/MobFarmManager#14]
Hi, has have issues for long time with mobcap in mfm.

It does not listen, on the Entity Types categor , especially for Water-animals.
It does it decently in nether but not in överworld, also other mobs it seems to have a hard time putting mobcap on, do not know if it is because it is both in Entity group and individual Entity Types category.

Wither skeleton it work fine with cap on Entity Types and Entity group.

server paper 1.16.4 296 (no other plugins) and try on 348 also 1.16.4 and test 1.16.4 400 papermc.

MFM version 1.5.9.0

config
https://pastebin.com/12EscVhC or here https://paste.helpch.at/esecebugus.bash

**Comment by Zrips** [comment]
After looking at your config file, you might want to consider enabling GroupChunks and setting GroupChunksRadius to 2, which will check for mob limits in 3x3 chunk area instead of checking single one which could have created this effect where in some places mobs seam to be limited while in other places its not. Well by default its only checking chunk where mob is located, so you can have 4x mobs in 2x2 area if its locate on edge of 4 chunks.

**Comment by broken1arrow** [comment]
> After looking at your config file, you might want to consider enabling GroupChunks and setting GroupChunksRadius to 2, which will check for mob limits in 3x3 chunk area instead of checking single one which could have created this effect where in some places mobs seam to be limited while in other places its not. Well by default its only checking chunk where mob is located, so you can have 4x mobs in 2x2 area if its locate on edge of 4 chunks.

Yes see that file was not 100% correctly what we use on the server (was settings from when i run it from testserver).

we use  ChunkRadius: 2  in EntitySpawn , but i see we has miss GroupChunks: to true.

But is probably because if you make one mistake in config.yml the plugin reset it and you has to start over if you not have backup (so can have miss fix that setting). You should make the plugin rename it too config.ymlerror or config.error and after that make new config.yml. 

will check now if it work :)

**Comment by broken1arrow** [comment]
> After looking at your config file, you might want to consider enabling GroupChunks and setting GroupChunksRadius to 2, which will check for mob limits in 3x3 chunk area instead of checking single one which could have created this effect where in some places mobs seam to be limited while in other places its not. Well by default its only checking chunk where mob is located, so you can have 4x mobs in 2x2 area if its locate on edge of 4 chunks.

yes, it seams it did the trick :) now the world not get flooded in squids :) and set it on GroupChunksRadius: 4
