### ISSUE TITLE
2.0.0.2 armor stand removal bug

### ISSUE THREAD

**Issue by slvlr** [Zrips/MobFarmManager#27]
Since updating to 2.0.0.2  playing have been unable to /sit at spawn using the GSit plugin. We realized that this may be because there are a lot of armor stands and holograms at spawn. I tried placing a normal armor stand, and it did get removed, by the auto-removal setting in mfm.

I changed the limit of armor stands from 25, to 100. And tried to place another armor stand. It still removed the 1 armor stand.
There is clearly not 100 armor stands in this area, and is a bug in the latest version.

I went back to version 2.0.0.1 with the same settings, and I could place armor stands just fine, without them getting removed. And players could now /sit again.

Other server owners are having the same issue as this.

**Comment by raphtaliapt** [comment]
I'm having the same issue.

**Comment by Zrips** [comment]
Confirmed, will issue fix with todays update
