### ISSUE TITLE
Item frames not being limited properly 

### ISSUE THREAD

**Issue by hotspuraz** [Zrips/MobFarmManager#28]
Hey Zrips,

There seems to be an issue with item frames and glow item frames. 
I have set both to be limited to 6, however, I can place +1 (7) normal item frames and then unlimited glow frames. They are later removed with cleanup but players who don't know they are limited will lose lots of item frames and make lots of complaints about it as a result x)
Glow item frames also don't get the "You can't place item frame in this chunk. Max allowed it 6!" 

https://user-images.githubusercontent.com/38726257/143491961-4fac2a48-c71d-4f16-a549-34c85a2bad0c.mp4

**Comment by Zrips** [comment]
Will introduce better compatibility for glow item frames as those currently haven't been handled as regular item frames.
