### ISSUE TITLE
Enderdragon unable to spawn

### ISSUE THREAD

**Issue by CaliDreams** [Zrips/MobFarmManager#3]
Upon The_end world load or respawning with crystals, the enderdragon's healthbar appears on the screen after the pillar crystals have finished spawning in, but the dragon entity does not spawn, and there is no dragon sound when using MobFarmManager 1.5.6.0.
- Patiently waited by the end portal each time as a constant
- Dragon DOES spawn correctly when I used MobFarmManager 1.5.5.1 with my Paper 1.15.2 server.

(tested over a dozen times without plugins on two different version servers...)

Tested on:
- Clean server with Paper build #378 for 1.15.2 and MobFarmManager 1.5.6.0
- Clean server with Paper build #93 for 1.16.1 and MobFarmManager 1.5.6.0

<cross-tested with MobFarmManager version 1.5.5.1 that I've been using on my 1.15.2 server flawlessly>

**Comment by broken1arrow** [comment]
> 
> 
> Upon The_end world load or respawning with crystals, the enderdragon's healthbar appears on the screen after the pillar crystals have finished spawning in, but the dragon entity does not spawn, and there is no dragon sound when using MobFarmManager 1.5.6.0.
> 
>     * Patiently waited by the end portal each time as a constant
> 
>     * Dragon DOES spawn correctly when I used MobFarmManager 1.5.5.1 with my Paper 1.15.2 server.
> 
> 
> (tested over a dozen times without plugins on two different version servers...)
> 
> Tested on:
> 
>     * Clean server with Paper build #378 for 1.15.2 and MobFarmManager 1.5.6.0
> 
>     * Clean server with Paper build #93 for 1.16.1 and MobFarmManager 1.5.6.0
> 
> 
> <cross-tested with MobFarmManager version 1.5.5.1 that I've been using on my 1.15.2 server flawlessly>

Even 1.5.5.3 work better on 1.16 and you have to set limit higher an 1 (if you set 1 Enderdragon not spawn). But see game breaking (for players) bugs in 1.5.6.0 and 1.5.7.0. It strange not more report this.

**Comment by BlindMag** [comment]
Having the same issue. Ender dragon boss bar shows up and no ender dragon appears.

**Comment by mrfloris** [comment]
Removing the end dragon doesn't trigger the event the game normally does. So a bossbar might still show I guess. 
The same seems to happen when we cmi killall enderdragon.

**Comment by Zrips** [comment]
Was resolved with latest versions
