### ISSUE TITLE
Entity Groups?

### ISSUE THREAD

**Issue by Blzd87** [Zrips/MobFarmManager#30]
[code=YAML]EntityGroups:
  Animals:
    Use: true
    Limit: 100
    List:
    - Villager
    - Pig
    - Cow
    - Sheep
    - Chicken
    - Axolotl
    - Wolf
    - Cat
    Worlds:
    - world
    - world_nether
    - world_the_end[/code]

Ive noticed this setup allows upto 100 of EACH type of mob in this group.

I thought it would limit this entire group to 100 so like 50 villagers 20 cows 20 pigs and 10 chickens for eg.. but Nope this plugin doesnt work that way...  so much for me being able to limit players to 100 mobs of that entire group...

unless my config is wrong please help!

**Comment by Zrips** [comment]
I will need entire config file you have with information what type of server you are running. In general this feature does work and it will limit mobs in defined groups, so something else interfering here.
