### ISSUE TITLE
1.18.1 PurPur TPS drops when cleaning mobs.

### ISSUE THREAD

**Issue by TomLewis** [Zrips/MobFarmManager#31]
I think theres a performance issue when the auto cleaning entities happens on 1.18.1, I'm using PurPur, we only started to notice it when more people got on the server.

```
This server is running Purpur version git-Purpur-1497 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9c51f21 on HEAD)
CMILib version 1.1.0.7
MobFarmManager version 2.0.1.0
```

**Comment by mrfloris** [comment]
Hey there, sorry to hear you're having this issue, I haven't noticed this on my own Paper 1.18.1 servers yet. 

To get better support, and help debug this potential issue, please provide the following information; 

The full output of:
```
ver
ver CMILib
ver MobFarmManager
```
Your configuration .yml file, and the steps to reproduce this issue.

We can't assist if we don't have any reasonable information to help look into this. 

How many users and it's fine, after how many does it go wrong?
Do they have massive farms?

It's made for Paper and Spigot, have you tried with a default configuration file and paper with the amount of users that it gives you a lag spike?

Can you run an hour long timings report or sparks one? So there's some info to go on?

**Comment by TomLewis** [comment]
Updated with versions.

**Comment by Zrips** [comment]
Without appropriate timings we cant really know if there are any lag spikes in general or if there are, if those are caused by MFM or another plugin. Just run some timings and when lag spike happens let us know with included timings link.
