### ISSUE TITLE
Block Limit Issue on Paper 1.12.2 Server

### ISSUE THREAD

**Issue by zSteley** [Zrips/MobFarmManager#32]
I can't place chests in the floor, because I have limit to 9! 
But.. if you do a tower you can place unlimited chests!

Short Clip Bug: https://youtu.be/ZDi-yxsOXvA

Server version: Paper 1.12.2
Plugin version: 2.0.1.0
CMILib version: 1.1.0.7

My config: __https://paste.md-5.net/zuyozafotu.bash__

Thanks!

**Comment by Zrips** [comment]
Will introduce new method. Main issue is that internal minecraft code doesn't detect chests as actual blocks which isint an issue with newer minecraft versions. But it should be up and running properly with next version.

**Comment by zSteley** [comment]
Not fixed yet

https://youtu.be/87q77dfvulE

@Zrips

**Comment by zSteley** [comment]
news?

**Comment by elmaslarry** [comment]
@Zrips

**Comment by elmaslarry** [comment]
No news?

**Comment by elmaslarry** [comment]
¿?

**Comment by zSteley** [comment]
@Zrips

**Comment by zSteley** [comment]
news?

**Comment by mrfloris** [comment]
No need to keep bumping, while i understand the frustration of not getting a timely response. It will be checked when there's free time to do so.

**Comment by Zrips** [comment]
Posted new version, should be more robust now with situations like this.
