### ISSUE TITLE
Player_head on the ground it doesnt get limit

### ISSUE THREAD

**Issue by UnitedCraft** [Zrips/MobFarmManager#34]
MobFarmManager version 2.0.2.1
Mob Farm Manager
Author: Zrips

CMILib version 1.1.0.8
CMI library
Website: https://www.spigotmc.org/resources/cmilib.87610/
Author: Zrips

Checking version, please wait...
his server is running Purpur version git-Purpur-1474 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 1c9c6b9 on HEAD)

Screenshoot:
https://imgur.com/a/pRlMY2P

**Comment by mrfloris** [comment]
I will soon have some time to try and check for this to reproduce it, can you confirm this is still happening when you use CMILib version `1.1.1.0` ?

I hope @Zrips also has time to look into this so not more servers are being 'tested'. Normally servers don't really get access to a huge amount of heads. Do you have any additional information on how to reproduce this? Can you as a non-team player place an x amount of heads in a chunk, bypassing the MFM limit and what's the number that starts causing lag for you? 

We are pretty generous with heads as rewards on my own survival servers, and I see players who have over 200 heads in chunks as decoration and besides client-side performance issues, it has no impact on the server that I can notice. So some additional information would be really helpful.

Can you also include the configuration part as you have it, so we know how you've got your mfm configured and what the expected limit is you have set?

**Comment by UnitedCraft** [comment]
so I checked on the latest CMIlib and the problem occurs, but it works weird. You would have to see it for yourself

I know players' heads are a problem, and that's the client side. Only such a player invites him to himself via teleportation, the other player gets a huge lag (client side) and can do nothing. During this time, he is killed and robbed and this destroys the community of the server. And it gets a problem

`
BlockTypes:
  Limit: true
  List:
    PLAYER_WALL_HEAD: 10
    PLAYER_HEAD: 10
    SCULK_SENSOR: 1
    `
    
 
_Do you have any additional information on how to reproduce this?_

Just place it as it is on the screen below:


![image](https://user-images.githubusercontent.com/79587189/153240218-1b25916f-e2a1-47a2-b3e1-8e7fc0acaeec.png)

**Comment by mrfloris** [comment]
I cannot reproduce this client side lag with the vanilla 1.18.1 client using Paper 1.18.1
I've placed 16x16 of a player head and even tried with 32 different skins. Asking others to tp to me, they get a tiny spike according to some, but they also have 250+ ms ping. Probably no different than them typing /rtp for example.

Can you perhaps run a timings report for a new chunk, with heads like that, and wait a minute and ask someone to teleport who is affected by this, and then wait another minute or so and repeat. And share the timings report? Maybe that can shed some light. 

Any other plugins on the server that deal with claims, regions, chunks, residences, or things like that? 

Do you get the same when you use item frames with items in them, or signs, or chests filled with things? Or is it only placed heads.

**Comment by UnitedCraft** [comment]
> Asking others to tp to me, they get a tiny spike according to some, but they also have 250+ ms ping. Probably no different than them typing /rtp for example.

The problem is not that players have little lag. The problem is that limiting player_head placed on ground is not working properly. And the player can put a lot of them.

I've already seen a player have over 350 heads with different skins and it caused a lot of lag on the player side.

So on the new server I want to limit it and I want mfm to help me with it, but this feature is not working properly.

Just fix it the limit player_head on ground and it'll be over

**Comment by mrfloris** [comment]
Thanks for all the extra info, that helps. If zrips needs more im sure he will ask for it.

**Comment by Zrips** [comment]
@UnitedCraft 
At this point I would try checking if player has access to mfm.bypasslimit.player_head permission node which can allow to bypass this limitation in general. 
Other than this, i might need your config file to check if something with that could cause this issue

**Comment by UnitedCraft** [comment]
> @UnitedCraft At this point I would try checking if player has access to mfm.bypasslimit.player_head permission node which can allow to bypass this limitation in general. Other than this, i might need your config file to check if something with that could cause this issue

Players has no permissions from MFM. 
But player head on walls works correct -> player_wall_head, but player_head placed on the ground doesnt work.

Here is my config file:
https://pastebin.com/eDGD4Jaw

I have tried different vaules from 10 to 5 to 1, and also 0. And nothig.

**Comment by Zrips** [comment]
Ok, identified silly bug, will make a fix and should be working correctly with next update. Sorry for inconvenience.
