### ISSUE TITLE
[Mob Farm Manager] Is it possible to manage mobs and blocks of other components

### ISSUE THREAD

**Issue by FZDNSZYT** [Zrips/MobFarmManager#38]
[Mob Farm Manager] Is it possible to manage mobs and blocks of other components, such as: [Slimefun4], and some plugins for more mobs and more monsters. I'm mainly asking about the ability to limit the number of placements, limit the number of spawns, and clean up too many entities. Will it throw an error?

**Comment by Zrips** [comment]
Entities are limited by their base type and any custom mob will be treated as vanilla ones if type of the mob matches.
