### ISSUE TITLE
Mobfarmanager removes mobs when the server spawn it - 1.18.2

### ISSUE THREAD

**Issue by UnitedCraft** [Zrips/MobFarmManager#43]
Hello, there is such a problem. I have a limit of e.g. 10 chickens for 3x3 chunks.
However, what happens is that in this area the server will naturally spawn the chickens and those in the fence are removed according to the limit. How to set that the server does not spawn these chickens over limit, or that those that already exist on the chunk will not be removed?

**Comment by Zrips** [comment]
Should be resolved with next version.
