### ISSUE TITLE
Error with GadgetsMenu

### ISSUE THREAD

**Issue by Snele** [Zrips/MobFarmManager#49]
MobFarmLimiter should not try to remove pets from GadgetsMenu plugin
However, he does it and this error occurs (and other plugins may work poorly because of it)
Please, fix it!

Error - https://pastebin.com/6ecVzSnQ

**Comment by Zrips** [comment]
Error is with GadgetsMenu not processing properly basic bukkit API call as Entity@getType(). I can add basic error catcher at that place to more or less ignore broken entities, but this should be more properly fixed at GadgetsMenu side.
