### ISSUE TITLE
Bug in HopperControl in version 1.19.4.

### ISSUE THREAD

**Issue by Stabrinai** [Zrips/MobFarmManager#50]
Server version: 1.19.4
Plugin version: 2.0.4.1

When Hopper Control is enabled.
The following warning will be triggered when there is a hopper around the player and the hopper is transferring items.

https://pastebin.com/zYF29DAP

**Comment by mercurialmusic** [comment]
Here to confirm and upvote, got the same in my testing on Paper b468. Spams the living hell out of console lol.

**Comment by Zrips** [comment]
Will be fixed with today's update
