### ISSUE TITLE
Chekpistonpush

### ISSUE THREAD

**Issue by DiktatorAladeen** [Zrips/MobFarmManager#58]
Hi,

Checkpistonpush variable is only blocking slime from moving from one chunk to another. But if players is moving other pistons, sticky pistons or observers to another chunks, he still bypassing limit ov that blocks in other chunk.

Can you fix that?

**Comment by DiktatorAladeen** [comment]
![image](https://github.com/Zrips/MobFarmManager/assets/34982264/bf3cee13-8085-4156-aaf5-e38e72cb3360)
Limit is 80 pistons per chunk, and look this!

He is moving like this:
![image](https://github.com/Zrips/MobFarmManager/assets/34982264/b790b065-da98-4287-a131-fa61b5ca41a9)

**Comment by Zrips** [comment]
Should be resolved with next update
