### ISSUE TITLE
Folia 1.20.4 compability problem (error spam)

### ISSUE THREAD

**Issue by DarkyG2** [Zrips/MobFarmManager#62]
When putting the plugin on my server and starting it, I'm getting this error spammed on Folia 1.20.4. Everything in the config is default btw: https://pastebin.com/56y5uJsJ

I'm on:
- CMILIB 1.4.5.0
- MobFarmManager 2.1.0.5
- Folia 1.20.4

**Comment by DarkyG2** [comment]
Found a quick fix that this plugin did: https://github.com/TownyAdvanced/Towny/commit/12ba98958bbc84fc49f503bc7d4e8dce9a1b146b

**Comment by Zrips** [comment]
New version with a fix should be out today.
