### ISSUE TITLE
itemframe's place limit was not incorrect.

### ISSUE THREAD

**Issue by Ecilpse** [Zrips/MobFarmManager#65]
i set limit itemframe's place limit to 10, but player can place 11 item frames.
(2.1.0.6)
![2024-03-24_22 50 36](https://github.com/Zrips/MobFarmManager/assets/25452835/2b0e39e4-1c5e-4ee9-8ee0-5daabae985f4)
![image](https://github.com/Zrips/MobFarmManager/assets/25452835/c10cb7e2-664a-4271-8ef3-7012a5c1ad37)

**Comment by Zrips** [comment]
Should be resolved with latest builds
