### ISSUE TITLE
About the expanded range of AutoClean function

### ISSUE THREAD

**Issue by siulung201314** [Zrips/MobFarmManager#70]
Before version 3.0.0.0,
If the expaned range is used and groupchunk is disabled, it will check **each** chunk near a player and count the number of animals in **each** chunk near a player respectively.

However, in version 3.0.0.0 or above,
If the expaned range is used and groupchunk is disabled, it check **all** chunks near a player and count the total number of animals in **all** chunks near a player.
This duplicates the function of group chunk.

I hope that the function of expaned range(before version 3.0.0.0) will be back because I would like to limit the number of animals in **each** chunk near a player, not the total number of animals in **all** chunks near a player.

**Comment by Zrips** [comment]
Will be fixed with next update
