### ISSUE TITLE
"HopperControl" module disables the suction of minecart hoppers on 1.20.6 & 1.21

### ISSUE THREAD

**Issue by Chevels** [Zrips/MobFarmManager#71]
Following the discovery of this issue we tested on 2 different servers (and different versions):
- paper 1.20.6 (_latest build_)
- paper 1.21 (_latest build_)

MobFarmManager tested versions are:
- 3.0.0.0
- 3.0.0.1

The bug reproduces on the 2 versions of the plugin, as well as on the 2 latest releases of Minecraft (_1.20.6 and 1.21_).

How to reproduce:
When MFM is installed and the ### HopperControl module is set to `Enabled: true` the minecart hopper loses suction in the following cases:
1/ when you unload the chunk in which there is a minecart hopper, then you return, the minecart hopper no longer sucks. It must be destroyed and replaced for the suction to work again; until the chunk is unloaded...

2/ when a minecart hopper passes over a hopper (_placed under the rail_) which therefore sucks up its contents, this instantly deactivates the suction of the minecart hopper. There too it will never regain its suction as long as we do not destroy it.
One of my mods made a video to show the problem. It is in French but the images are enough:
https://github.com/Zrips/MobFarmManager/assets/8831222/fad75af4-a392-4eb2-bd6a-ee606e9951bf

This makes minecart hoppers unusable which is problematic.

Until Zrips can correct this, to fix the problem we have to set the **HopperControl** module to `Enabled: false`

HopperControl has become a must have to save the performance of our servers, I hope this bug can be fixed without too much difficulty.

Thanks for your work ! :)

**Comment by Zrips** [comment]
Should be resolved with next update
