### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by BronzWarq** [Zrips/MobFarmManager#74]
With latest version and all others between 3.0.0.3 and latest i have same crash 

[crash-2024-07-08_17.47.15-server.txt](https://github.com/user-attachments/files/16134016/crash-2024-07-08_17.47.15-server.txt)
[2024-07-08-5.log](https://github.com/user-attachments/files/16134017/2024-07-08-5.log)

**Comment by Zrips** [comment]
Next version should resolve this issue
