### ISSUE TITLE
When I set "NATURAL" to "false" mobs still spawn naturally

### ISSUE THREAD

**Issue by vicevil77** [Zrips/MobFarmManager#76]
When I set in Spawn Reasons "NATURAL" to "false" they continue to spawn and many more

**Comment by Zrips** [comment]
As comments above it indicate this section will only define which type of spawning we are monitoring, when setting Natural to false will mean that any naturally spawned entity will be ignored when checking its spawn event. If you want to disable natural spawning of particular entities then you can do it in EntityTypes section by setting `NaturalSpawn: false` as shown in first example

**Comment by vicevil77** [comment]
It keep Spawning Naturally what other solution I have?
