### ISSUE TITLE
EntityGroups for itemframe & armorstand

### ISSUE THREAD

**Issue by Ecilpse** [Zrips/MobFarmManager#83]
![image](https://github.com/user-attachments/assets/be332724-b354-4e06-b9e4-357968f9318d)
![image](https://github.com/user-attachments/assets/5e590946-19ee-41da-96db-3e557aba7e8f)

The entity group between armorstand, itemframe, and glow_item_frame is not working properly.
place can place 10 each, not 10 in total.

**Comment by Zrips** [comment]
Will be fixed with next build
